name: nutanix
distribution_spec:
  description: Use Nutanix AI Endpoint for running LLM inference
  providers:
    inference: remote::nutanix
    memory: inline::faiss
    safety: inline::llama-guard
    agents: inline::meta-reference
    telemetry: inline::meta-reference
